name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - 1.x

permissions:
  contents: write
  pull-requests: write

env:
  HUSKY: 0

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: 1.x

      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Build
        run: |
          bun install --frozen-lockfile
          bun run build
        if: ${{ steps.release.outputs.release_created }}
      - run: bun publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
